# create User

POST  http://localhost:3000/user 
Content-Type: application/json

{
        "username": "demo8",
        "password": "demo8"
}
    
######update User
PUT http://localhost:3000/user/15
Content-Type: application/json

{
    "username": "demo5_updated",
    "password": "newpassword"
}

### Delete User
DELETE http://localhost:3000/user/15