### Create user 
POST http://localhost:3000/user 
Content-Type: application/json

{
"username": "demo5", "password": "demo5"
}

### Update user 
PUT http://localhost:3000/user 
Content-Type: application/json

{
"id": 1, "username": "demo1", "password": "demo_pass"
}

### Delete user 
DELETE http://localhost:3000/user 
Content-Type: application/json

{
"id": 7
}

### Search user 
GET http://localhost:3000/user/search?q=d 
Content-Type: application/json